#!/usr/bin/env bash

# Gets all tags for a given docker image.

# Examples:

# retrieve all tags for a single library
# docker-tags "library/redis" | jq --raw-output '.[]'

# retrieve all tags for multiple libraries
# docker-tags "library/mongo" "library/redis" "microsoft/nanoserver" "microsoft/dotnet" | jq --raw-output '.[]'

# retrieve first 10 tags for multiple libraries
# docker-tags "library/mongo" "library/redis" "microsoft/nanoserver" "microsoft/dotnet" | jq --raw-output '.[][0:9]'

# Kudos go to https://gist.github.com/robv8r/fa66f5e0fdf001f425fe9facf2db6d49
DEFAULT_FILTER="^[0-9][^r|c]*alpine$"

docker-latest-tag() {
  image="$1"
  filter=${2:-$DEFAULT_FILTER}
  tags=`wget -q https://registry.hub.docker.com/v1/repositories/${image}/tags -O -  | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}' | grep -E "${filter}" | sort -Vr | head -n1`

  # tags=` echo "${tags}" | grep "$2" `
  echo ${tags}
}

docker-check-tag() {
  image="$1"
  filter=${2:-$DEFAULT_FILTER}
  tags=`wget -q https://registry.hub.docker.com/v1/repositories/${image}/tags -O -  | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}' | grep -E "${filter}" | sort -Vr`

  # tags=` echo "${tags}" | grep "$2" `
  echo ${tags}
}

docker-tags() {
  arr=("$@")

  for item in "${arr[@]}";
  do
    tokenUri="https://auth.docker.io/token"
    data=("service=registry.docker.io" "scope=repository:$item:pull")
    token="$(curl --silent --get --data-urlencode ${data[0]} --data-urlencode ${data[1]} $tokenUri | jq --raw-output '.token')"
    listUri="https://registry-1.docker.io/v2/$item/tags/list"
    authz="Authorization: Bearer $token"
    result="$(curl --silent --get -H "Accept: application/json" -H "Authorization: Bearer $token" $listUri | jq --raw-output '.')"
    echo $result
  done
}

# Entrypoint in case this script is run directly.
if [[ "$0" == *"docker-tags" ]]
then
  docker-check-tag "$@"
fi
