#!/usr/bin/env bash

DEFAULT_VERSION_REGEX="v\d+(\.\d+)+$"

latest-git-tag() {
  local handle=$1
  local repo=$2
  local versionRegex=${3:-$DEFAULT_VERSION_REGEX}
  echo $(git ls-remote --tags --sort="v:refname" https://github.com/$handle/$repo.git 2>/dev/null | grep -Po "$versionRegex" | tail -n1 | sed 's/.*\///; s/\^{}//')
}

check-git-tag() {
  local handle=$1
  local repo=$2
  local version=$3
  local versionRegex=${4:-$DEFAULT_VERSION_REGEX}
  git ls-remote --tags --sort="v:refname" https://github.com/$handle/$repo.git 2>/dev/null | grep -Po "$versionRegex" | grep $version | sed 's/.*\///; s/\^{}//'
}

# Entrypoint in case this script is run directly.
script_name=$(basename "$0")
if [[ "$script_name" == "git-tags" ]]; then
  eval $@
elif [[ "$script_name" == "latest-git-tag" ]]; then
  latest-git-tag $@
elif [[ "$script_name" == "check-git-tag" ]]; then
  check-git-tag $@
fi