#!/usr/bin/env bash

DEFAULT_VERSION_REGEX="v\d+(\.\d+)+$"

latest-git-tag() {
  local handle=$1
  local repo=$2
  local versionRegex=${3:-$DEFAULT_VERSION_REGEX}
  echo $(git ls-remote --tags --sort="v:refname" https://github.com/$handle/$repo.git 2>/dev/null | grep -Po "$versionRegex" | tail -n1 | sed 's/.*\///; s/\^{}//')
}

check-git-tag() {
  local handle=$1
  local repo=$2
  local version=$3
  local versionRegex=${4:-$DEFAULT_VERSION_REGEX}
  git ls-remote --tags --sort="v:refname" https://github.com/$handle/$repo.git 2>/dev/null | grep -Po "$versionRegex" | grep $version | sed 's/.*\///; s/\^{}//'
}

# Entrypoint in case this script is run directly.
if [[ "$0" == *"git-tags" ]]
then
  eval $(basename $0) $@
fi