title: Docker Containers
description: >-
  Automated container management system with intelligent upstream monitoring,
  version classification, and CI/CD pipelines.
baseurl: ""
url: "https://oorabona.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Content settings
show_excerpts: true

# Navigation
header_pages:
  - dashboard.md
  - docs/index.md

# Footer
github_username: oorabona

# Include only specific files for Jekyll build (allowlist approach)
include:
  - "_*"           # Jekyll directories (_layouts, _includes, etc.)
  - "*.md"         # All markdown files
  - "*.html"       # All HTML files
  - "docs/"        # Documentation directory
  - "assets/"      # Assets directory (CSS, images, etc.)
  - "_config.yml"  # This config file

# Only exclude absolute essentials (override Jekyll defaults)
exclude:
  - node_modules/
  - vendor/
  - Gemfile*
