title: Docker Containers
description: >-
  Automated container management system with intelligent upstream monitoring,
  version classification, and CI/CD pipelines.
baseurl: ""
url: "https://oorabona.github.io"

# Build settings
markdown: kramdown
theme: minima  # Keep as fallback, but we'll override with Tabler
plugins:
  - jekyll-feed

# Content settings
show_excerpts: true

# Navigation
header_pages:
  - dashboard.md
  - docs/index.md

# Footer
github_username: oorabona

# Custom settings for Tabler integration
tabler:
  version: "1.4.0"
  cdn: true  # Use CDN for faster loading
  
# SEO and metadata
title_separator: " | "
description_extra: "Docker container monitoring dashboard"

# Whitelist approach: exclude everything, then include only what Jekyll needs
exclude:
  - "**"            # Exclude everything first

include:
  - "_config.yml"   # This Jekyll config file
  - "*.md"          # Root-level markdown files (README, DASHBOARD, etc.)
  - "docs/**"       # All documentation content
  - "_*"            # Jekyll system directories (layouts, includes, etc.)
