version: '3'
services:
  mysql-workbench:
    image: oorabona/mysql-workbench
    network_mode: host
    volumes:
      - /tmp/.X11-unix
      - $HOME/.mysql-workbench:/root/.mysql/workbench
    environment:
      DISPLAY: unix$DISPLAY
