# Base PostgreSQL flavor
# Standard PostgreSQL with built-in extensions only
# No compiled extensions, smallest image size

name: base
description: "Standard PostgreSQL with built-in extensions"

# No compiled extensions
extensions: []

# Built-in extensions to enable by default
builtin_extensions:
  - pg_stat_statements
  - pgcrypto
  - uuid-ossp
  - btree_gin
  - btree_gist
  - pg_trgm

# shared_preload_libraries setting
shared_preload_libraries:
  - pg_stat_statements

# Image tags to publish
tags:
  - "{version}-alpine"          # e.g., 17.5-alpine
  - "{major}-alpine"            # e.g., 17-alpine
  - "{version}-base-alpine"     # e.g., 17.5-base-alpine
  - "{major}-base-alpine"       # e.g., 17-base-alpine
