#!/bin/bash
# Integration test for WordPress + PHP-FPM + OpenResty stack (hardened)
set -euo pipefail

COMPOSE_FILE="$(dirname "$0")/docker-compose.yaml"
TIMEOUT=90

# Helper: run wp-cli in the WordPress container (stderr suppressed for PHP deprecation noise)
wp_exec() {
    docker compose -f "$COMPOSE_FILE" exec -T wordpress wp "$@" 2>/dev/null
}

cleanup() {
    echo "  Cleaning up..."
    docker compose -f "$COMPOSE_FILE" down -v --remove-orphans 2>/dev/null || true
}
trap cleanup EXIT

echo "  Testing WordPress Stack..."

# Start the stack (auto-install via WP_AUTO_INSTALL=true)
echo "  Starting services..."
docker compose -f "$COMPOSE_FILE" up -d 2>/dev/null

# Wait for WordPress to be ready (wp core version works without DB)
echo "  Waiting for WordPress to be ready..."
elapsed=0
while [ $elapsed -lt $TIMEOUT ]; do
    if wp_exec core version | grep -qE '^[0-9]'; then
        break
    fi
    sleep 5
    elapsed=$((elapsed + 5))
done

if [ $elapsed -ge $TIMEOUT ]; then
    echo "  FAIL: WordPress did not become ready in ${TIMEOUT}s"
    docker compose -f "$COMPOSE_FILE" logs 2>/dev/null || true
    exit 1
fi

# Wait for entrypoint auto-install + OpenResty startup
sleep 10

# Test: wp-config.php was generated by entrypoint
echo "  Checking wp-config.php generation..."
if wp_exec config path | grep -q "wp-config.php"; then
    echo "  OK wp-config.php generated"
else
    echo "  FAIL: wp-config.php not found"
    exit 1
fi

# Test: Security constants set in wp-config.php
echo "  Checking security hardening..."
if wp_exec config get DISALLOW_FILE_MODS | grep -q "1"; then
    echo "  OK DISALLOW_FILE_MODS is active"
else
    echo "  FAIL: DISALLOW_FILE_MODS not set"
    exit 1
fi

# Test: Database connectivity via wp-cli
echo "  Checking database connectivity..."
if wp_exec db query "SELECT 1" | grep -q "1"; then
    echo "  OK Database connection successful"
else
    echo "  FAIL: Cannot connect to MariaDB"
    exit 1
fi

# Test: WordPress was auto-installed
echo "  Checking auto-install..."
if wp_exec core is-installed; then
    echo "  OK WordPress auto-installed"
else
    echo "  FAIL: WordPress not installed (WP_AUTO_INSTALL failed)"
    exit 1
fi

# Test: Site title matches env var
echo "  Checking site configuration..."
if wp_exec option get blogname | grep -q "My WordPress Site"; then
    echo "  OK Site title configured correctly"
else
    echo "  FAIL: Site title does not match WP_SITE_TITLE"
    exit 1
fi

# Test: PHP-FPM executes WordPress code (end-to-end through wp-cli)
echo "  Checking PHP-FPM execution..."
if wp_exec eval 'echo "php-fpm-ok";' | grep -q "php-fpm-ok"; then
    echo "  OK PHP-FPM executing WordPress code"
else
    echo "  FAIL: PHP-FPM not executing WordPress code"
    exit 1
fi

# Test: OpenResty reachable on its PUBLISHED host port — guards both the
# non-root port migration and the compose `ports:` mapping (catches a wrong
# listen port, failed startup, broken FastCGI proxy, or a bad host mapping)
echo "  Checking OpenResty on its published host port..."
host_addr=$(docker compose -f "$COMPOSE_FILE" port openresty 8080 2>/dev/null || true)
if [ -z "$host_addr" ]; then
    echo "  FAIL: container port 8080 is not published (check the ports: mapping)"
    exit 1
fi
# `docker compose port` may print a wildcard host (0.0.0.0 / [::]); curl needs
# a routable loopback address.
host_addr="${host_addr/#0.0.0.0:/127.0.0.1:}"
host_addr="${host_addr/#\[::\]:/[::1]:}"
status=$(curl -sS -o /dev/null -w '%{http_code}' "http://${host_addr}/" 2>/dev/null || true)
if echo "$status" | grep -qE '^[23][0-9][0-9]$'; then
    echo "  OK OpenResty serving on the published port (HTTP $status)"
else
    echo "  FAIL: OpenResty did not return 2xx/3xx on the published port (got: ${status:-no response})"
    exit 1
fi

echo "  All WordPress Stack tests passed"
