name: Close Duplicate PRs
description: Closes existing PRs for the same container version update to prevent
  duplicates
inputs:
  container:
    description: Container name
    required: true
  new_version:
    description: New version being updated to
    required: true
  github_token:
    description: GitHub token for API access
    required: true
outputs:
  existing_pr_found:
    description: Whether an existing PR was found for this container/version combination
    value: ${{ steps.check_duplicates.outputs.existing_pr_found }}
runs:
  using: composite
  steps:
    - name: Setup jq
      uses: vegardit/gha-setup-jq@v1
      with:
        version: latest
    - name: Setup GitHub CLI
      id: setup_gh
      uses: ./.github/actions/setup-github-cli
      with:
        github_token: ${{ inputs.github_token }}
    - name: Close duplicate PRs
      id: check_duplicates
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        CONTAINER: ${{ inputs.container }}
        NEW_VERSION: ${{ inputs.new_version }}
      run: |
        # Check if GitHub CLI is available from setup step
        if [ "${{ steps.setup_gh.outputs.available }}" != "true" ]; then
          echo "⚠️  GitHub CLI not available, skipping PR cleanup"
          echo "ℹ️  This would work in GitHub Actions environment"
          echo "existing_pr_found=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Make the script executable and run it
        chmod +x .github/scripts/close-duplicate-prs.sh
        .github/scripts/close-duplicate-prs.sh
