services:
  debian:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        VERSION: "${VERSION:-latest}"
        LOCALES: "fr_FR en_US"
        USER: "${USER:-debian}"
        GROUP: "${GROUP:-debian}"
        USERID: "${UID:-1000}"
        GROUPID: "${GID:-1000}"
        SHELL: "${SHELL:-/bin/bash}"
        PASSWORD: "${PASSWORD:-password}"
    image: "debian:${VERSION:-latest}-fr"
    container_name: "debian-${VERSION:-latest}"
    environment:
      - DEBIAN_FRONTEND=noninteractive
    entrypoint: ["/bin/sh", "-c", "while :; do sleep 1; done"]  # Keep the container running
    network_mode: "host"