#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=../helpers/logging.sh
# shellcheck disable=SC1091
source "$ROOT_DIR/helpers/logging.sh"
# shellcheck source=../helpers/retry.sh
# shellcheck disable=SC1091
source "$ROOT_DIR/helpers/retry.sh"

usage() {
    cat >&2 <<'USAGE'
usage: open-key-lifecycle-issue.sh [--json-file findings.json]

Reads findings JSON from stdin when --json-file is omitted.
USAGE
}

run_gh() {
    retry_with_backoff 3 5 gh "$@"
}

validate_container() {
    [[ "$1" =~ ^[a-z0-9][a-z0-9._-]*$ ]]
}

md_cell() {
    local s="$1"
    s="${s//$'\r'/ }"
    s="${s//$'\n'/ }"
    s="${s//|/\\|}"
    s="${s//\`/\\\`}"
    printf '%s' "$s"
}

issue_number_from_list() {
    local title="$1"
    jq -r --arg t "$title" '[.[] | select(.title == $t)][0].number // empty' 2>/dev/null
}

config_reasons() {
    jq -r '
      def legacy_config_reasons:
        [.contract.reason?, .expiry.reason?, .rotation.reason?]
        | map(select(. != null))
        | map(select(. == "config-parse-error"
            or . == "config-shape-invalid"
            or . == "invalid-warn-days"
            or . == "gpg-key-shape-invalid"
            or . == "missing-pinned-fingerprint"
            or . == "missing-release-template"
            or . == "rotation-config-unsupported"
            or . == "rotation-tag-pattern-unsupported"
            or . == "key-file-missing"
            or . == "key-file-invalid"));

      if (.config? | type == "array" and length > 0) then
        [.config[]
          | if type == "object" then .reason else . end
          | select(. != null and . != "")]
      else
        legacy_config_reasons
      end
      | unique
      | .[]
    ' 2>/dev/null
}

issue_scope() {
    local finding="$1"
    local container dep
    container="$(jq -r '.container' <<< "$finding")"
    dep="$(jq -r '.dependency // ""' <<< "$finding")"
    if [[ -n "$dep" && "$dep" != "null" ]]; then
        printf '%s/%s' "$container" "$dep"
    else
        printf '%s' "$container"
    fi
}

ensure_issue_labels() {
    local container="$1"

    run_gh label create "automation" \
        --repo "$GITHUB_REPOSITORY" \
        --color "0e8a16" \
        --description "Automated process" \
        --force >/dev/null 2>&1 || true
    run_gh label create "gpg-key-lifecycle" \
        --repo "$GITHUB_REPOSITORY" \
        --color "d93f0b" \
        --description "Vendored GPG signing key lifecycle finding" \
        --force >/dev/null 2>&1 || true
    run_gh label create "container:${container}" \
        --repo "$GITHUB_REPOSITORY" \
        --color "e4e669" \
        --description "Container-scoped automation finding for ${container}" \
        --force >/dev/null 2>&1 || true
}

build_issue_body() {
    local kind="$1"
    local finding="$2"
    local container dep key_file fpr expires days_left latest status reason primary_fpr pinned_fpr primary_count primary_validity errors
    container="$(jq -r '.container' <<< "$finding")"
    dep="$(jq -r '.dependency // "unknown"' <<< "$finding")"
    key_file="$(jq -r '.key_file // ""' <<< "$finding")"
    fpr="$(jq -r '.expiry.fpr // ""' <<< "$finding")"

    if [[ "$kind" == "expiry" ]]; then
        expires="$(jq -r '.expiry.expires // "none"' <<< "$finding")"
        days_left="$(jq -r '.expiry.days_left // "unknown"' <<< "$finding")"
        status="$(jq -r '.expiry.status' <<< "$finding")"
        reason="$(jq -r '.expiry.reason' <<< "$finding")"
        cat <<BODY
## GPG signing key expiry finding

| Property | Value |
|----------|-------|
| **Container** | $(md_cell "$container") |
| **Dependency** | $(md_cell "$dep") |
| **Key file** | $(md_cell "$key_file") |
| **Signing key fingerprint** | $(md_cell "${fpr:-unknown}") |
| **Status** | $(md_cell "$status") |
| **Reason** | $(md_cell "$reason") |
| **Expires** | $(md_cell "$expires") |
| **Days left** | $(md_cell "$days_left") |

Review upstream signing key, re-vendor $(md_cell "$key_file") if rotated.

_Auto-generated by \`scripts/open-key-lifecycle-issue.sh\`_
BODY
    elif [[ "$kind" == "rotation" ]]; then
        latest="$(jq -r '.rotation.latest // "unknown"' <<< "$finding")"
        status="$(jq -r '.rotation.status' <<< "$finding")"
        reason="$(jq -r '.rotation.reason' <<< "$finding")"
        cat <<BODY
## Release signature verification finding

| Property | Value |
|----------|-------|
| **Container** | $(md_cell "$container") |
| **Dependency** | $(md_cell "$dep") |
| **Key file** | $(md_cell "$key_file") |
| **Signing key fingerprint** | $(md_cell "${fpr:-unknown}") |
| **Latest release** | $(md_cell "$latest") |
| **Status** | $(md_cell "$status") |
| **Reason** | $(md_cell "$reason") |

Review upstream signing key, re-vendor $(md_cell "$key_file") if rotated.

_Auto-generated by \`scripts/open-key-lifecycle-issue.sh\`_
BODY
    elif [[ "$kind" == "degraded" ]]; then
        latest="$(jq -r '.rotation.latest // "unknown"' <<< "$finding")"
        status="$(jq -r '.rotation.status' <<< "$finding")"
        reason="$(jq -r '.rotation.reason' <<< "$finding")"
        errors="$(jq -r '.errors // [] | join("; ")' <<< "$finding")"
        cat <<BODY
## GPG signing-key monitor degraded

| Property | Value |
|----------|-------|
| **Container** | $(md_cell "$container") |
| **Dependency** | $(md_cell "$dep") |
| **Key file** | $(md_cell "$key_file") |
| **Signing key fingerprint** | $(md_cell "${fpr:-unknown}") |
| **Latest release** | $(md_cell "$latest") |
| **Status** | $(md_cell "$status") |
| **Reason** | $(md_cell "$reason") |
| **Failure detail** | $(md_cell "${errors:-unknown}") |

The rotation check could not verify the latest upstream release with the
vendored signing key. This may be a transient upstream or network outage; the
issue body is refreshed by each monitor run. Once the check succeeds again, a
maintainer can close this issue.

_Auto-generated by \`scripts/open-key-lifecycle-issue.sh\`_
BODY
    elif [[ "$kind" == "config" ]]; then
        reason="$(config_reasons <<< "$finding" | paste -sd ',' -)"
        [[ -n "$reason" ]] || reason="config-error"
        status="$(jq -r --arg reason "$reason" '
          if (.config? | type == "array" and length > 0) then "error"
          elif .contract.reason == $reason then .contract.status
          elif .expiry.reason == $reason then .expiry.status
          elif .rotation.reason == $reason then .rotation.status
          else "error"
          end
        ' <<< "$finding")"
        errors="$(jq -r '.errors // [] | join("; ")' <<< "$finding")"
        cat <<BODY
## GPG key monitor configuration finding

| Property | Value |
|----------|-------|
| **Container** | $(md_cell "$container") |
| **Dependency** | $(md_cell "$dep") |
| **Key file** | $(md_cell "$key_file") |
| **Status** | $(md_cell "$status") |
| **Reason** | $(md_cell "$reason") |
| **Failure detail** | $(md_cell "${errors:-unknown}") |

Review the container's GPG key lifecycle monitor configuration before the next
scheduled check.

_Auto-generated by \`scripts/open-key-lifecycle-issue.sh\`_
BODY
    else
        status="$(jq -r '.contract.status // .expiry.status // "error"' <<< "$finding")"
        reason="$(jq -r '.contract.reason // .expiry.reason // "key-contract-mismatch"' <<< "$finding")"
        primary_fpr="$(jq -r '.contract.primary_fpr // "unknown"' <<< "$finding")"
        pinned_fpr="$(jq -r '.contract.pinned_fpr // "unknown"' <<< "$finding")"
        primary_count="$(jq -r '.contract.primary_count // "unknown"' <<< "$finding")"
        primary_validity="$(jq -r '.contract.primary_validity // "unknown"' <<< "$finding")"
        cat <<BODY
## GPG vendored key file finding

| Property | Value |
|----------|-------|
| **Container** | $(md_cell "$container") |
| **Dependency** | $(md_cell "$dep") |
| **Key file** | $(md_cell "$key_file") |
| **Pinned fingerprint** | $(md_cell "$pinned_fpr") |
| **Primary fingerprint** | $(md_cell "$primary_fpr") |
| **Primary count** | $(md_cell "$primary_count") |
| **Primary validity** | $(md_cell "$primary_validity") |
| **Status** | $(md_cell "$status") |
| **Reason** | $(md_cell "$reason") |

The vendored key file no longer satisfies the Dockerfile trust contract. Review
the key file and \`build_args\` pin before the next $(md_cell "$container") build.

_Auto-generated by \`scripts/open-key-lifecycle-issue.sh\`_
BODY
    fi
}

upsert_issue_once() {
    local container="$1"
    local title="$2"
    local labels="$3"
    local body="$4"
    local search_output existing_number

    ensure_issue_labels "$container"

    if ! search_output="$(gh issue list \
        --repo "$GITHUB_REPOSITORY" \
        --label "automation" \
        --label "gpg-key-lifecycle" \
        --label "container:${container}" \
        --state open \
        --limit 100 \
        --json number,title)"; then
        printf 'open-key-lifecycle-issue: gh issue list failed for title: %s\n' "$title" >&2
        return 1
    fi
    existing_number="$(printf '%s' "$search_output" | issue_number_from_list "$title")"

    if [[ -n "$existing_number" ]]; then
        if ! gh issue edit "$existing_number" \
            --repo "$GITHUB_REPOSITORY" \
            --body "$body" >/dev/null; then
            printf 'open-key-lifecycle-issue: gh issue edit failed for #%s title: %s\n' "$existing_number" "$title" >&2
            return 1
        fi
        echo "refreshed #${existing_number}"
    else
        local create_out
        if ! create_out="$(gh issue create \
            --repo "$GITHUB_REPOSITORY" \
            --title "$title" \
            --label "$labels" \
            --body "$body")"; then
            printf 'open-key-lifecycle-issue: gh issue create failed for title: %s\n' "$title" >&2
            return 1
        fi
        local number
        number="$(printf '%s' "$create_out" | grep -o '[0-9]*$' || true)"
        if [[ -z "$number" || ! "$number" =~ ^[0-9]+$ ]]; then
            printf 'open-key-lifecycle-issue: gh issue create succeeded but returned no issue number (output: %s)\n' "$create_out" >&2
            return 1
        fi
        echo "created #${number}"
    fi
}

open_or_comment_issue() {
    local kind="$1"
    local finding="$2"
    local container scope title labels body

    container="$(jq -r '.container' <<< "$finding")"
    validate_container "$container" || {
        printf '::warning::open-key-lifecycle-issue: invalid container name in finding; skipping\n' >&2
        return 0
    }
    scope="$(issue_scope "$finding")"

    labels="automation,gpg-key-lifecycle,container:${container}"
    if [[ "$kind" == "expiry" ]]; then
        title="[GPG key lifecycle] ${scope}: signing key expiring"
    elif [[ "$kind" == "rotation" ]]; then
        title="[GPG key lifecycle] ${scope}: release signature no longer verifies (rotation?)"
    elif [[ "$kind" == "degraded" ]]; then
        title="[GPG key lifecycle] ${scope}: signing-key monitor degraded (cannot verify latest release)"
    elif [[ "$kind" == "config" ]]; then
        title="[GPG key lifecycle] ${scope}: monitor configuration problem"
    else
        title="[GPG key lifecycle] ${scope}: vendored key file problem (build-breaking)"
    fi
    body="$(build_issue_body "$kind" "$finding")"

    retry_with_backoff 3 5 upsert_issue_once "$container" "$title" "$labels" "$body"
}

process_findings() {
    local findings="$1"
    local issue_failures=0

    if ! jq -e 'type == "array"' >/dev/null <<< "$findings"; then
        echo "open-key-lifecycle-issue: findings JSON must be an array" >&2
        return 2
    fi

    local row
    while IFS= read -r row; do
        [[ -z "$row" ]] && continue
        local expiry_severity expiry_reason rotation_status rotation_reason rotation_runtime key_reason config_reason
        expiry_severity="$(jq -r '.expiry.severity // "none"' <<< "$row")"
        expiry_reason="$(jq -r '.expiry.reason // ""' <<< "$row")"
        rotation_status="$(jq -r '.rotation.status // "ok"' <<< "$row")"
        rotation_reason="$(jq -r '.rotation.reason // ""' <<< "$row")"
        rotation_runtime="$(jq -r '.rotation.runtime // "auto"' <<< "$row")"
        key_reason="$(jq -r '
          [.contract.reason?, .expiry.reason?, .rotation.reason?]
          | map(select(. != null))
          | map(select(. == "key-contract-mismatch"
              or . == "key-parse-error"))
          | .[0] // ""
        ' <<< "$row")"
        config_reason="$(config_reasons <<< "$row" | head -n 1)"

        if [[ -n "$key_reason" ]]; then
            if ! open_or_comment_issue "contract" "$row"; then
                printf 'open-key-lifecycle-issue: issue operation failed for contract finding; continuing\n' >&2
                issue_failures=$((issue_failures + 1))
            fi
            if [[ -n "$config_reason" ]] && ! open_or_comment_issue "config" "$row"; then
                printf 'open-key-lifecycle-issue: issue operation failed for config finding; continuing\n' >&2
                issue_failures=$((issue_failures + 1))
            fi
            continue
        elif [[ -n "$config_reason" ]]; then
            if ! open_or_comment_issue "config" "$row"; then
                printf 'open-key-lifecycle-issue: issue operation failed for config finding; continuing\n' >&2
                issue_failures=$((issue_failures + 1))
            fi
        fi

        case "$expiry_severity" in
            warn|high)
                if [[ "$expiry_reason" == "expiring" || "$expiry_reason" == "expired" || "$expiry_reason" == "signing-key-expired" ]]; then
                    if ! open_or_comment_issue "expiry" "$row"; then
                        printf 'open-key-lifecycle-issue: issue operation failed for expiry finding; continuing\n' >&2
                        issue_failures=$((issue_failures + 1))
                    fi
                fi
                ;;
        esac
        if [[ "$rotation_status" == "rotation" ]]; then
            if ! open_or_comment_issue "rotation" "$row"; then
                printf 'open-key-lifecycle-issue: issue operation failed for rotation finding; continuing\n' >&2
                issue_failures=$((issue_failures + 1))
            fi
        elif [[ "$rotation_status" == "error" && "$rotation_reason" == "rotation-check-unavailable" \
            && ( "$rotation_runtime" == "true" || ( "$rotation_runtime" == "auto" && -z "$config_reason" ) ) ]]; then
            if ! open_or_comment_issue "degraded" "$row"; then
                printf 'open-key-lifecycle-issue: issue operation failed for degraded finding; continuing\n' >&2
                issue_failures=$((issue_failures + 1))
            fi
        fi
    done < <(jq -c '.[]' <<< "$findings")

    if (( issue_failures > 0 )); then
        printf 'open-key-lifecycle-issue: %d issue operation(s) failed\n' "$issue_failures" >&2
        return 1
    fi
}

main() {
    : "${GH_TOKEN:?GH_TOKEN is required}"
    : "${GITHUB_REPOSITORY:?GITHUB_REPOSITORY is required}"

    local json_file="" findings
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --json-file)
                [[ $# -ge 2 ]] || {
                    usage
                    return 2
                }
                json_file="$2"
                shift 2
                ;;
            -*)
                usage
                return 2
                ;;
            *)
                usage
                return 2
                ;;
        esac
    done

    if [[ -n "$json_file" ]]; then
        findings="$(cat "$json_file")"
    else
        findings="$(cat)"
    fi

    process_findings "$findings"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    main "$@"
fi
