#!/bin/bash
set -ex
[[ "$WANTED" == "latest" ]] && exit 1

docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx create --name builder --driver docker-container --use
docker buildx inspect --bootstrap
docker buildx build --push --build-arg RESTY_J=${NPROC} --build-arg ENABLE_HTTP_PROXY_CONNECT=true --build-arg RESTY_VERSION=${VERSION:latest} --platform=linux/arm/v7,linux/amd64 -t oorabona/openresty-http-connect:${TAG} -t oorabona/openresty-http-connect:latest .
docker buildx build --push --build-arg RESTY_J=${NPROC} --build-arg ENABLE_HTTP_PROXY_CONNECT=false --build-arg RESTY_VERSION=${VERSION:latest} --platform=linux/arm/v7,linux/amd64 -t oorabona/openresty:${TAG} -t oorabona/openresty:latest .
docker buildx rm builder
