version: '3'
services:
  mysql-workbench:
    image: oorabona/mysql-workbench:${TAG:-latest}
    build:
      context: .
      args:
        OS_VERSION: ${VERSION}
    network_mode: host
    volumes:
      - /tmp/.X11-unix
      - $HOME/.mysql-workbench:/root/.mysql/workbench
    environment:
      DISPLAY: unix$DISPLAY
